### ISSUE TITLE
TASK-28: Employee Register Validation Fixes

### ISSUE THREAD

**Issue by bsptech** [bsp-tech/itcommunity_frontend#56]
1. cv path required olacaq ve regex ile yazilan datanin "https:// ve ya http://" ile bashlanildigi yoxlanilacaq. 
2.github - required ol-M-ayacaq ve regex ile yazilan datanin "https://github.com/" ile bashlanildigi yoxlanilacaq. (axirdaki slash de)
2. linkedin - required ol-M-ayacaq ve regex ile yazilan datanin "https://linkedin.com/in/" ile bashlanildigi yoxlanilacaq. (axirdaki slash de)

**Comment by Jale93** [comment]
Validation Fixed

**Comment by bsptech** [comment]
github ve linkedin-in regex-ine bele bir shey elave etmek lazimdir ki, null ola bilsin ve ya regex odensin. Null ola bilsin sohbetini regex-e pattern kimi elave etmek lazimdir. Eks halda regex filter edecek ve deyecek ki, shertler odenmir. Hetta sen annotation ile nullable etsen bele.

Cv path ise oldugu kimi qalsin chunki cv path mutleq doldurulmalidir.
